name: TreeRegen
version: '${project.version}'
main: me.xcrownn.treeregen.TreeRegen
api-version: 1.17
authors: [ xCrownn ]
description: Trees Regenerate after a set amount of time.
depend:
  - WorldEdit
  - WorldGuard
softdepend:
  - FastAsyncWorldEdit
commands:
  setTree:
    usage: </command>
  removeTree:
    usage: </command>
